export type EmailAudience = 'guest' | 'host' | 'system';
export type EmailStatus = 'shipped' | 'in-progress' | 'planned' | 'parked';

export interface EmailTemplateSpec {
  slug: string;
  name: string;
  audience: EmailAudience;
  category: string;
  trigger: string;
  description: string;
  status: EmailStatus;
  templatePath?: string;
  serviceFunction?: string;
}

export const EMAIL_TEMPLATES: EmailTemplateSpec[] = [
  // Guest — Booking Flow
  {
    slug: 'booking-confirmation',
    name: 'Booking Confirmation',
    audience: 'guest',
    category: 'Booking Flow',
    trigger: 'Stripe payment intent succeeded',
    description: 'Full booking summary with stay dates, total paid, links to guides and guest book.',
    status: 'shipped',
    templatePath: 'src/emails/BookingConfirmationEmail.tsx',
    serviceFunction: 'sendBookingConfirmation',
  },
  {
    slug: 'receipt',
    name: 'Receipt / Payment Confirmation',
    audience: 'guest',
    category: 'Booking Flow',
    trigger: 'Stripe webhook or manual resend',
    description: 'Detailed line-item receipt matching Stripe amounts.',
    status: 'shipped',
    templatePath: 'src/emails/ReceiptEmail.tsx',
    serviceFunction: 'sendReceiptEmail',
  },
  {
    slug: 'booking-details-welcome',
    name: 'Booking Details / Welcome Email',
    audience: 'guest',
    category: 'Booking Flow',
    trigger: 'Immediately after booking confirmed',
    description: 'High-level welcome with property summary, house rules, and helpful links.',
    status: 'shipped',
    templatePath: 'src/emails/BookingWelcomeEmail.tsx',
    serviceFunction: 'sendBookingWelcomeEmail',
  },

  // Guest — Stay Preparation
  {
    slug: 'pre-stay-48h',
    name: '48-Hour Pre-Stay Reminder',
    audience: 'guest',
    category: 'Stay Preparation',
    trigger: 'Cron: 48 hours before check-in',
    description: 'Reminder featuring check-in instructions, guest book, weather, and helpline.',
    status: 'shipped',
    templatePath: 'src/emails/PreStayReminderEmail.tsx',
    serviceFunction: 'sendPreStayReminder',
  },
  {
    slug: 'pre-stay-24h',
    name: '24-Hour Pre-Stay Reminder',
    audience: 'guest',
    category: 'Stay Preparation',
    trigger: 'Cron: 24 hours before check-in',
    description: 'Additional reminder for long trips or remote/winter destinations.',
    status: 'shipped',
    templatePath: 'src/emails/PreStay24hEmail.tsx',
    serviceFunction: 'sendPreStay24hReminder',
  },
  {
    slug: 'door-code-delivery',
    name: 'Door Code / Smart Lock Delivery',
    audience: 'guest',
    category: 'Stay Preparation',
    trigger: 'When lock code generated or updated',
    description: 'Secure delivery of access codes, parking instructions, and lock guidance.',
    status: 'shipped',
    templatePath: 'src/emails/DoorCodeEmail.tsx',
    serviceFunction: 'sendDoorCodeEmail',
  },


  // Guest — During Stay
  {
    slug: 'mid-stay-check-in',
    name: 'Mid-Stay Check-In',
    audience: 'guest',
    category: 'During Stay',
    trigger: 'Cron: morning of day 2',
    description: 'Concierge style check-in with optional upsells and support contact.',
    status: 'shipped',
    templatePath: 'src/emails/MidStayCheckInEmail.tsx',
    serviceFunction: 'sendMidStayCheckIn',
  },
  {
    slug: 'issue-report-confirmation',
    name: 'Issue / Maintenance Report Confirmation',
    audience: 'guest',
    category: 'During Stay',
    trigger: 'Guest submits maintenance/damage report',
    description: 'Acknowledges report receipt and outlines next steps.',
    status: 'shipped',
    templatePath: 'src/emails/IssueReportConfirmationEmail.tsx',
    serviceFunction: 'sendIssueReportConfirmation',
  },
  {
    slug: 'noise-warning',
    name: 'Noise Warning / Courtesy Notification',
    audience: 'guest',
    category: 'During Stay',
    trigger: 'Manual send or noise monitoring alert',
    description: 'Polite reminder to reduce noise and respect community guidelines.',
    status: 'shipped',
    templatePath: 'src/emails/NoiseWarningEmail.tsx',
    serviceFunction: 'sendNoiseWarning',
  },

  // Guest — Departure & Post-Stay
  {
    slug: 'checkout-reminder',
    name: 'Checkout Reminder',
    audience: 'guest',
    category: 'Departure & Post-Stay',
    trigger: 'Cron: evening before checkout',
    description: 'Checkout time, cleaning guidelines, parking reminders, and lock-up steps.',
    status: 'shipped',
    templatePath: 'src/emails/CheckoutReminderEmail.tsx',
    serviceFunction: 'sendCheckoutReminder',
  },
  {
    slug: 'post-stay-thank-you',
    name: 'Post-Stay Thank You',
    audience: 'guest',
    category: 'Departure & Post-Stay',
    trigger: 'Within 12 hours after checkout',
    description: 'Thank you note plus rebooking incentives or referral links.',
    status: 'shipped',
    templatePath: 'src/emails/PostStayThankYouEmail.tsx',
    serviceFunction: 'sendPostStayThankYou',
  },
  {
    slug: 'review-request',
    name: 'Review Request',
    audience: 'guest',
    category: 'Departure & Post-Stay',
    trigger: 'Cron: 24 hours after checkout',
    description: 'Personalized CTA to leave a review, optionally with incentive.',
    status: 'shipped',
    templatePath: 'src/emails/ReviewRequestEmail.tsx',
    serviceFunction: 'sendReviewRequest',
  },
  {
    slug: 'guest-refund-issued',
    name: 'Guest Refund Issued',
    audience: 'guest',
    category: 'Departure & Post-Stay',
    trigger: 'Partial refund processed',
    description: 'Explains refund amount, method, and expected timeline.',
    status: 'shipped',
    templatePath: 'src/emails/GuestRefundIssuedEmail.tsx',
    serviceFunction: 'sendGuestRefundIssued',
  },

  // Guest — Edge Cases
  {
    slug: 'cancellation-confirmation',
    name: 'Cancellation Confirmation',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Booking cancellation event',
    description: 'Summarizes refund policy, retained fees, and rebooking links.',
    status: 'shipped',
    templatePath: 'src/emails/CancellationConfirmationEmail.tsx',
    serviceFunction: 'sendCancellationConfirmation',
  },
  {
    slug: 'booking-modification-confirmation',
    name: 'Booking Modification Confirmation',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Booking update (dates, guests, payouts)',
    description: 'Confirms the change and updated totals.',
    status: 'shipped',
    templatePath: 'src/emails/BookingModificationEmail.tsx',
    serviceFunction: 'sendBookingModificationConfirmation',
  },
  {
    slug: 'no-show-notification',
    name: 'No-Show Notification',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Booking flagged as no-show',
    description: 'Outlines charges incurred and rebooking options.',
    status: 'shipped',
    templatePath: 'src/emails/NoShowNotificationEmail.tsx',
    serviceFunction: 'sendNoShowNotification',
  },
  {
    slug: 'payment-failure',
    name: 'Payment Failure / Retry Request',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Stripe payment requires further action',
    description: 'Guides guest through completing payment or using a new method.',
    status: 'shipped',
    templatePath: 'src/emails/PaymentFailureEmail.tsx',
    serviceFunction: 'sendPaymentFailure',
  },
  {
    slug: 'deposit-release',
    name: 'Hold Deposit Release Confirmation',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Security deposit released',
    description: 'Confirms deposit release and expected bank timing.',
    status: 'shipped',
    templatePath: 'src/emails/DepositReleaseEmail.tsx',
    serviceFunction: 'sendDepositRelease',
  },

  // Host — Booking Notifications
  {
    slug: 'host-new-booking',
    name: 'New Booking Alert',
    audience: 'host',
    category: 'Booking Notifications',
    trigger: 'Booking marked paid',
    description: 'Guest details, stay dates, payout estimate, and special requests.',
    status: 'shipped',
    templatePath: 'src/emails/HostNotificationEmail.tsx',
    serviceFunction: 'sendHostNotification',
  },

  {
    slug: 'host-booking-modified',
    name: 'Booking Modification Alert',
    audience: 'host',
    category: 'Booking Notifications',
    trigger: 'Booking updated',
    description: 'Highlights changed dates, pricing, or guest counts.',
    status: 'shipped',
    templatePath: 'src/emails/HostBookingModifiedEmail.tsx',
    serviceFunction: 'sendHostBookingModified',
  },

  // Host — Pre-Stay Prep
  {
    slug: 'host-prep-3-day',
    name: '3-Day Pre-Arrival Host Reminder',
    audience: 'host',
    category: 'Pre-Stay Prep',
    trigger: 'Cron: 3 days before arrival',
    description: 'Covers cleaning schedule and special requests.',
    status: 'shipped',
    templatePath: 'src/emails/HostPrepThreeDayEmail.tsx',
    serviceFunction: 'sendHostPrepThreeDay',
  },
  {
    slug: 'host-prep-same-day',
    name: 'Same-Day Arrival Host Reminder',
    audience: 'host',
    category: 'Pre-Stay Prep',
    trigger: 'Morning of check-in',
    description: 'Final ETA, notes, and support contact.',
    status: 'shipped',
    templatePath: 'src/emails/HostPrepSameDayEmail.tsx',
    serviceFunction: 'sendHostPrepSameDay',
  },
  {
    slug: 'host-door-code-reminder',
    name: 'Door Code Setup Reminder',
    audience: 'host',
    category: 'Pre-Stay Prep',
    trigger: 'Dynamic lock workflows',
    description: 'Ensures smart lock credentials are ready.',
    status: 'shipped',
    templatePath: 'src/emails/HostDoorCodeReminderEmail.tsx',
    serviceFunction: 'sendHostDoorCodeReminder',
  },

  // Host — Edge Cases
  {
    slug: 'host-guest-cancelled',
    name: 'Guest Cancelled Booking',
    audience: 'host',
    category: 'Edge Cases',
    trigger: 'Guest cancellation',
    description: 'Explains payout changes and calendar state.',
    status: 'shipped',
    templatePath: 'src/emails/HostGuestCancelledEmail.tsx',
    serviceFunction: 'sendHostGuestCancelled',
  },
  {
    slug: 'host-no-show',
    name: 'No-Show Guest',
    audience: 'host',
    category: 'Edge Cases',
    trigger: 'No-show flagged',
    description: 'Summarizes charges and next steps.',
    status: 'shipped',
    templatePath: 'src/emails/HostNoShowEmail.tsx',
    serviceFunction: 'sendHostNoShow',
  },
  {
    slug: 'host-refund-adjustment',
    name: 'Refund Adjustment Notice',
    audience: 'host',
    category: 'Edge Cases',
    trigger: 'Refund issued to guest',
    description: 'Notifies host of payout impact.',
    status: 'shipped',
    templatePath: 'src/emails/HostRefundAdjustmentEmail.tsx',
    serviceFunction: 'sendHostRefundAdjustment',
  },
  {
    slug: 'host-chargeback',
    name: 'Chargeback / Dispute Alert',
    audience: 'host',
    category: 'Edge Cases',
    trigger: 'Stripe dispute webhook',
    description: 'Warns host about dispute timeline and required action.',
    status: 'shipped',
    templatePath: 'src/emails/HostChargebackEmail.tsx',
    serviceFunction: 'sendHostChargebackAlert',
  },




];
