export type EmailAudience = 'guest' | 'host' | 'system';
export type EmailStatus = 'shipped' | 'in-progress' | 'planned' | 'parked';

export interface EmailTemplateSpec {
  slug: string;
  name: string;
  audience: EmailAudience;
  category: string;
  trigger: string;
  description: string;
  status: EmailStatus;
  templatePath?: string;
  serviceFunction?: string;
}

export const EMAIL_TEMPLATES: EmailTemplateSpec[] = [
  // Guest — Booking Flow
  {
    slug: 'booking-confirmation',
    name: 'Booking Confirmation',
    audience: 'guest',
    category: 'Booking Flow',
    trigger: 'Stripe payment intent succeeded',
    description: 'Full booking summary with stay dates, total paid, links to guides and guest book.',
    status: 'shipped',
    templatePath: 'src/emails/BookingConfirmationEmail.tsx',
    serviceFunction: 'sendBookingConfirmation',
  },
  {
    slug: 'receipt',
    name: 'Receipt / Payment Confirmation',
    audience: 'guest',
    category: 'Booking Flow',
    trigger: 'Stripe webhook or manual resend',
    description: 'Detailed line-item receipt matching Stripe amounts.',
    status: 'shipped',
    templatePath: 'src/emails/ReceiptEmail.tsx',
    serviceFunction: 'sendReceiptEmail',
  },
  {
    slug: 'booking-details-welcome',
    name: 'Booking Details / Welcome Email',
    audience: 'guest',
    category: 'Booking Flow',
    trigger: 'Immediately after booking confirmed',
    description: 'High-level welcome with property summary, house rules, and helpful links.',
    status: 'shipped',
    templatePath: 'src/emails/BookingWelcomeEmail.tsx',
    serviceFunction: 'sendBookingWelcomeEmail',
  },

  // Guest — Stay Preparation
  {
    slug: 'pre-stay-48h',
    name: '48-Hour Pre-Stay Reminder',
    audience: 'guest',
    category: 'Stay Preparation',
    trigger: 'Cron: 48 hours before check-in',
    description: 'Reminder featuring check-in instructions, guest book, weather, and helpline.',
    status: 'shipped',
    templatePath: 'src/emails/PreStayReminderEmail.tsx',
    serviceFunction: 'sendPreStayReminder',
  },
  {
    slug: 'pre-stay-24h',
    name: '24-Hour Pre-Stay Reminder',
    audience: 'guest',
    category: 'Stay Preparation',
    trigger: 'Cron: 24 hours before check-in',
    description: 'Additional reminder for long trips or remote/winter destinations.',
    status: 'shipped',
    templatePath: 'src/emails/PreStay24hEmail.tsx',
    serviceFunction: 'sendPreStay24hReminder',
  },
  {
    slug: 'door-code-delivery',
    name: 'Door Code / Smart Lock Delivery',
    audience: 'guest',
    category: 'Stay Preparation',
    trigger: 'When lock code generated or updated',
    description: 'Secure delivery of access codes, parking instructions, and lock guidance.',
    status: 'shipped',
    templatePath: 'src/emails/DoorCodeEmail.tsx',
    serviceFunction: 'sendDoorCodeEmail',
  },


  // Guest — During Stay
  {
    slug: 'mid-stay-check-in',
    name: 'Mid-Stay Check-In',
    audience: 'guest',
    category: 'During Stay',
    trigger: 'Cron: morning of day 2',
    description: 'Concierge style check-in with optional upsells and support contact.',
    status: 'shipped',
    templatePath: 'src/emails/MidStayCheckInEmail.tsx',
    serviceFunction: 'sendMidStayCheckIn',
  },
  {
    slug: 'issue-report-confirmation',
    name: 'Issue / Maintenance Report Confirmation',
    audience: 'guest',
    category: 'During Stay',
    trigger: 'Guest submits maintenance/damage report',
    description: 'Acknowledges report receipt and outlines next steps.',
    status: 'shipped',
    templatePath: 'src/emails/IssueReportConfirmationEmail.tsx',
    serviceFunction: 'sendIssueReportConfirmation',
  },
  {
    slug: 'noise-warning',
    name: 'Noise Warning / Courtesy Notification',
    audience: 'guest',
    category: 'During Stay',
    trigger: 'Manual send or noise monitoring alert',
    description: 'Polite reminder to reduce noise and respect community guidelines.',
    status: 'shipped',
    templatePath: 'src/emails/NoiseWarningEmail.tsx',
    serviceFunction: 'sendNoiseWarning',
  },

  // Guest — Departure & Post-Stay
  {
    slug: 'checkout-reminder',
    name: 'Checkout Reminder',
    audience: 'guest',
    category: 'Departure & Post-Stay',
    trigger: 'Cron: evening before checkout',
    description: 'Checkout time, cleaning guidelines, parking reminders, and lock-up steps.',
    status: 'shipped',
    templatePath: 'src/emails/CheckoutReminderEmail.tsx',
    serviceFunction: 'sendCheckoutReminder',
  },
  {
    slug: 'post-stay-thank-you',
    name: 'Post-Stay Thank You',
    audience: 'guest',
    category: 'Departure & Post-Stay',
    trigger: 'Within 12 hours after checkout',
    description: 'Thank you note plus rebooking incentives or referral links.',
    status: 'shipped',
    templatePath: 'src/emails/PostStayThankYouEmail.tsx',
    serviceFunction: 'sendPostStayThankYou',
  },
  {
    slug: 'review-request',
    name: 'Review Request',
    audience: 'guest',
    category: 'Departure & Post-Stay',
    trigger: 'Cron: 24 hours after checkout',
    description: 'Personalized CTA to leave a review, optionally with incentive.',
    status: 'shipped',
    templatePath: 'src/emails/ReviewRequestEmail.tsx',
    serviceFunction: 'sendReviewRequest',
  },
  {
    slug: 'guest-refund-issued',
    name: 'Guest Refund Issued',
    audience: 'guest',
    category: 'Departure & Post-Stay',
    trigger: 'Partial refund processed',
    description: 'Explains refund amount, method, and expected timeline.',
    status: 'shipped',
    templatePath: 'src/emails/GuestRefundIssuedEmail.tsx',
    serviceFunction: 'sendGuestRefundIssued',
  },

  // Guest — Edge Cases
  {
    slug: 'cancellation-confirmation',
    name: 'Cancellation Confirmation',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Booking cancellation event',
    description: 'Summarizes refund policy, retained fees, and rebooking links.',
    status: 'shipped',
    templatePath: 'src/emails/CancellationConfirmationEmail.tsx',
    serviceFunction: 'sendCancellationConfirmation',
  },
  {
    slug: 'booking-modification-confirmation',
    name: 'Booking Modification Confirmation',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Booking update (dates, guests, payouts)',
    description: 'Confirms the change and updated totals.',
    status: 'shipped',
    templatePath: 'src/emails/BookingModificationEmail.tsx',
    serviceFunction: 'sendBookingModificationConfirmation',
  },
  {
    slug: 'no-show-notification',
    name: 'No-Show Notification',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Booking flagged as no-show',
    description: 'Outlines charges incurred and rebooking options.',
    status: 'shipped',
    templatePath: 'src/emails/NoShowNotificationEmail.tsx',
    serviceFunction: 'sendNoShowNotification',
  },
  {
    slug: 'payment-failure',
    name: 'Payment Failure / Retry Request',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Stripe payment requires further action',
    description: 'Guides guest through completing payment or using a new method.',
    status: 'shipped',
    templatePath: 'src/emails/PaymentFailureEmail.tsx',
    serviceFunction: 'sendPaymentFailure',
  },
  {
    slug: 'deposit-release',
    name: 'Hold Deposit Release Confirmation',
    audience: 'guest',
    category: 'Edge Cases',
    trigger: 'Security deposit released',
    description: 'Confirms deposit release and expected bank timing.',
    status: 'shipped',
    templatePath: 'src/emails/DepositReleaseEmail.tsx',
    serviceFunction: 'sendDepositRelease',
  },

  // Host — Booking Notifications
  {
    slug: 'host-new-booking',
    name: 'New Booking Alert',
    audience: 'host',
    category: 'Booking Notifications',
    trigger: 'Booking marked paid',
    description: 'Guest details, stay dates, payout estimate, and special requests.',
    status: 'shipped',
    templatePath: 'src/emails/HostNotificationEmail.tsx',
    serviceFunction: 'sendHostNotification',
  },

  {
    slug: 'host-booking-modified',
    name: 'Booking Modification Alert',
    audience: 'host',
    category: 'Booking Notifications',
    trigger: 'Booking updated',
    description: 'Highlights changed dates, pricing, or guest counts.',
    status: 'shipped',
    templatePath: 'src/emails/HostBookingModifiedEmail.tsx',
    serviceFunction: 'sendHostBookingModified',
  },

  // Host — Pre-Stay Prep
  {
    slug: 'host-prep-3-day',
    name: '3-Day Pre-Arrival Host Reminder',
    audience: 'host',
    category: 'Pre-Stay Prep',
    trigger: 'Cron: 3 days before arrival',
    description: 'Covers cleaning schedule and special requests.',
    status: 'shipped',
    templatePath: 'src/emails/HostPrepThreeDayEmail.tsx',
    serviceFunction: 'sendHostPrepThreeDay',
  },
  {
    slug: 'host-prep-same-day',
    name: 'Same-Day Arrival Host Reminder',
    audience: 'host',
    category: 'Pre-Stay Prep',
    trigger: 'Morning of check-in',
    description: 'Final ETA, notes, and support contact.',
    status: 'shipped',
    templatePath: 'src/emails/HostPrepSameDayEmail.tsx',
    serviceFunction: 'sendHostPrepSameDay',
  },
  {
    slug: 'host-door-code-reminder',
    name: 'Door Code Setup Reminder',
    audience: 'host',
    category: 'Pre-Stay Prep',
    trigger: 'Dynamic lock workflows',
    description: 'Ensures smart lock credentials are ready.',
    status: 'shipped',
    templatePath: 'src/emails/HostDoorCodeReminderEmail.tsx',
    serviceFunction: 'sendHostDoorCodeReminder',
  },

  // Host — During Stay
  {
    slug: 'host-damage-report',
    name: 'Damage / Incident Report from Guest',
    audience: 'host',
    category: 'During Stay',
    trigger: 'Guest submits incident form',
    description: 'Includes photos/details for rapid response.',
    status: 'shipped',
    templatePath: 'src/emails/HostDamageReportEmail.tsx',
    serviceFunction: 'sendHostDamageReport',
  },
  {
    slug: 'host-cleaner-report',
    name: 'Cleaner Maintenance Report',
    audience: 'host',
    category: 'During Stay',
    trigger: 'Cleaner logs issue post-clean',
    description: 'Surfaces maintenance findings to host.',
    status: 'shipped',
    templatePath: 'src/emails/HostCleanerReportEmail.tsx',
    serviceFunction: 'sendHostCleanerReport',
  },
  {
    slug: 'host-noise-alert',
    name: 'Noise Alert Notification',
    audience: 'host',
    category: 'During Stay',
    trigger: 'Noise monitoring event',
    description: 'Alerts hosts to potential disturbances.',
    status: 'shipped',
    templatePath: 'src/emails/HostNoiseAlertEmail.tsx',
    serviceFunction: 'sendHostNoiseAlert',
  },

  // Host — After Stay
  {
    slug: 'host-checkout-confirmed',
    name: 'Checkout Confirmed',
    audience: 'host',
    category: 'After Stay',
    trigger: 'Smart lock or cleaner confirms departure',
    description: 'Notifies host property is vacated.',
    status: 'shipped',
    templatePath: 'src/emails/HostCheckoutConfirmedEmail.tsx',
    serviceFunction: 'sendHostCheckoutConfirmed',
  },
  {
    slug: 'host-cleaner-assigned',
    name: 'Cleaner Assigned / Completed Notification',
    audience: 'host',
    category: 'After Stay',
    trigger: 'Cleaner scheduling + completion events',
    description: 'Confirms turnovers are scheduled or done.',
    status: 'shipped',
    templatePath: 'src/emails/HostCleanerAssignedEmail.tsx',
    serviceFunction: 'sendHostCleanerAssigned',
  },

  // Host — Edge Cases
  {
    slug: 'host-guest-cancelled',
    name: 'Guest Cancelled Booking',
    audience: 'host',
    category: 'Edge Cases',
    trigger: 'Guest cancellation',
    description: 'Explains payout changes and calendar state.',
    status: 'shipped',
    templatePath: 'src/emails/HostGuestCancelledEmail.tsx',
    serviceFunction: 'sendHostGuestCancelled',
  },
  {
    slug: 'host-no-show',
    name: 'No-Show Guest',
    audience: 'host',
    category: 'Edge Cases',
    trigger: 'No-show flagged',
    description: 'Summarizes charges and next steps.',
    status: 'shipped',
    templatePath: 'src/emails/HostNoShowEmail.tsx',
    serviceFunction: 'sendHostNoShow',
  },
  {
    slug: 'host-refund-adjustment',
    name: 'Refund Adjustment Notice',
    audience: 'host',
    category: 'Edge Cases',
    trigger: 'Refund issued to guest',
    description: 'Notifies host of payout impact.',
    status: 'shipped',
    templatePath: 'src/emails/HostRefundAdjustmentEmail.tsx',
    serviceFunction: 'sendHostRefundAdjustment',
  },
  {
    slug: 'host-chargeback',
    name: 'Chargeback / Dispute Alert',
    audience: 'host',
    category: 'Edge Cases',
    trigger: 'Stripe dispute webhook',
    description: 'Warns host about dispute timeline and required action.',
    status: 'shipped',
    templatePath: 'src/emails/HostChargebackEmail.tsx',
    serviceFunction: 'sendHostChargebackAlert',
  },

  // Host — Onboarding
  {
    slug: 'host-onboarding-welcome',
    name: 'Welcome to Bunks',
    audience: 'host',
    category: 'Onboarding',
    trigger: 'Host onboarding completion',
    description: 'Shares onboarding guide and support contacts.',
    status: 'shipped',
    templatePath: 'src/emails/HostOnboardingWelcomeEmail.tsx',
    serviceFunction: 'sendHostOnboardingWelcome',
  },
  {
    slug: 'host-verification-progress',
    name: 'Property Verification Progress',
    audience: 'host',
    category: 'Onboarding',
    trigger: 'Ops verification milestone',
    description: 'Updates host on verification status and required actions.',
    status: 'shipped',
    templatePath: 'src/emails/HostVerificationProgressEmail.tsx',
    serviceFunction: 'sendHostVerificationProgress',
  },
  {
    slug: 'host-listing-ready',
    name: 'Listing Imported / Ready to Review',
    audience: 'host',
    category: 'Onboarding',
    trigger: 'Listing auto-build completion',
    description: 'Invites host to review AI-generated listing.',
    status: 'shipped',
    templatePath: 'src/emails/HostListingReadyEmail.tsx',
    serviceFunction: 'sendHostListingReady',
  },

  // System / Internal
  {
    slug: 'system-email-failed',
    name: 'Failed Email Delivery',
    audience: 'system',
    category: 'System Alerts',
    trigger: 'Postmark bounce webhook',
    description: 'Alerts ops to a bounced/blocked email.',
    status: 'shipped',
    templatePath: 'src/emails/SystemEmailFailedEmail.tsx',
    serviceFunction: 'sendSystemEmailFailed',
  },
  {
    slug: 'system-stripe-webhook-failed',
    name: 'Stripe Webhook Failed',
    audience: 'system',
    category: 'System Alerts',
    trigger: 'Webhook handler error',
    description: 'Escalation when Stripe events fail processing.',
    status: 'shipped',
    templatePath: 'src/emails/SystemStripeWebhookFailedEmail.tsx',
    serviceFunction: 'sendSystemStripeWebhookFailed',
  },
  {
    slug: 'system-booking-creation-failed',
    name: 'Booking Creation Failed',
    audience: 'system',
    category: 'System Alerts',
    trigger: 'Booking API failure',
    description: 'Notifies admins when booking creation errors occur.',
    status: 'shipped',
    templatePath: 'src/emails/SystemBookingCreationFailedEmail.tsx',
    serviceFunction: 'sendSystemBookingCreationFailed',
  },
  {
    slug: 'system-cron-summary',
    name: 'Cron Summary',
    audience: 'system',
    category: 'System Alerts',
    trigger: 'Post-cron run summary',
    description: 'Digest summarizing reminder/review sends.',
    status: 'shipped',
    templatePath: 'src/emails/SystemCronSummaryEmail.tsx',
    serviceFunction: 'sendSystemCronSummary',
  },
  {
    slug: 'system-major-issue',
    name: 'Major Issue Reported',
    audience: 'system',
    category: 'System Alerts',
    trigger: 'Guest/host marks issue as major',
    description: 'Escalates critical incidents internally.',
    status: 'shipped',
    templatePath: 'src/emails/SystemMajorIssueEmail.tsx',
    serviceFunction: 'sendSystemMajorIssue',
  },
  {
    slug: 'system-calendar-sync-error',
    name: 'Calendar Sync Error',
    audience: 'system',
    category: 'System Alerts',
    trigger: 'Airbnb iCal import failure',
    description: 'Warns team about calendar sync issues.',
    status: 'shipped',
    templatePath: 'src/emails/SystemCalendarSyncErrorEmail.tsx',
    serviceFunction: 'sendSystemCalendarSyncError',
  },
  {
    slug: 'system-payment-exception',
    name: 'Payment Exception Detected',
    audience: 'system',
    category: 'System Alerts',
    trigger: 'Payment anomaly, partial capture, etc.',
    description: 'Surfaced for finance/ops follow-up.',
    status: 'shipped',
    templatePath: 'src/emails/SystemPaymentExceptionEmail.tsx',
    serviceFunction: 'sendSystemPaymentException',
  },
];
