export const SUPPORTED_SAMPLE_TEMPLATE_SLUGS = [
  'booking-confirmation',
  'receipt',
  'booking-details-welcome',
  'pre-stay-48h',
  'pre-stay-24h',
  'door-code-delivery',
  'add-on-confirmation',
  'mid-stay-check-in',
  'issue-report-confirmation',
  'noise-warning',
  'checkout-reminder',
  'post-stay-thank-you',
  'review-request',
  'guest-refund-issued',
  'cancellation-confirmation',
  'booking-modification-confirmation',
  'no-show-notification',
  'payment-failure',
  'deposit-release',
  'host-new-booking',
  'host-add-on-sold',
  'host-booking-modified',
  'host-prep-3-day',
  'host-prep-same-day',
  'host-door-code-reminder',
  'host-damage-report',
  'host-cleaner-report',
  'host-noise-alert',
  'host-checkout-confirmed',
  'host-cleaner-assigned',
  'host-guest-cancelled',
  'host-no-show',
  'host-refund-adjustment',
  'host-chargeback',
  'host-onboarding-welcome',
  'host-verification-progress',
  'host-listing-ready',
  'system-email-failed',
  'system-stripe-webhook-failed',
  'system-booking-creation-failed',
  'system-cron-summary',
  'system-major-issue',
  'system-calendar-sync-error',
  'system-payment-exception',
] as const;

export type SampleTemplateSlug = (typeof SUPPORTED_SAMPLE_TEMPLATE_SLUGS)[number];

export function isSampleTemplateSlug(slug: string): slug is SampleTemplateSlug {
  return (SUPPORTED_SAMPLE_TEMPLATE_SLUGS as readonly string[]).includes(slug);
}
